name: fluter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  http: 1.3.0
  nested: ^1.0.0
  provider: ^6.0.0
  weather: ^3.0.0 
  google_fonts: ^6.1.0 

  

dev_dependencies:
  blackfoot_flutter_lint: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  
flutter_launcher_icons:
  android: true
  ios: true
  windows: 
    generate: true
    image_path: "documentation/app icon.jpg"
  web:
    generate: true
    image_path: "documentation/app icon.jpg"
  image_path: "documentation/app icon.jpg"


flutter:
 uses-material-design: true
 assets:
   - documentation/pic.png
   - documentation/pic1.png
   - documentation/pic2.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
 

  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
